// Mock data for job listings
export const jobListings = [
    {
      id: 1,
      title: "Senior Frontend Developer",
      company: "TechCorp Inc.",
      location: "San Francisco, CA",
      salary: "$120,000 - $150,000",
      type: "Full-time",
      posted: "2 days ago",
      description: "We are looking for an experienced Frontend Developer to join our team...",
      tags: ["React", "TypeScript", "Next.js"],
    },
    {
      id: 2,
      title: "UX/UI Designer",
      company: "DesignHub",
      location: "Remote",
      salary: "$90,000 - $110,000",
      type: "Full-time",
      posted: "1 week ago",
      description: "Join our creative team to design beautiful and intuitive user interfaces...",
      tags: ["Figma", "Adobe XD", "UI/UX"],
    },
    {
      id: 3,
      title: "DevOps Engineer",
      company: "CloudSystems",
      location: "New York, NY",
      salary: "$130,000 - $160,000",
      type: "Full-time",
      posted: "3 days ago",
      description: "Looking for a DevOps engineer to help us scale our infrastructure...",
      tags: ["AWS", "Docker", "Kubernetes"],
    },
    {
      id: 4,
      title: "Product Manager",
      company: "ProductLabs",
      location: "Austin, TX",
      salary: "$110,000 - $140,000",
      type: "Full-time",
      posted: "5 days ago",
      description: "We need a product manager to lead our product development efforts...",
      tags: ["Agile", "Product Strategy", "Roadmapping"],
    },
    {
      id: 5,
      title: "Data Scientist",
      company: "DataInsights",
      location: "Remote",
      salary: "$125,000 - $155,000",
      type: "Contract",
      posted: "1 day ago",
      description: "Join our data science team to build machine learning models...",
      tags: ["Python", "Machine Learning", "SQL"],
    },
  ]